conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from page.views import home_page_view, new_detail_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("page.urls", namespace="page"))

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

page/urls.py
from django.urls import path

from page.views import new_detail_page, home_page_view, add_email

app_name = "page"

urlpatterns = [
    path('news/<int:pk>', new_detail_page, name="news-detail"),
    path('email/', add_email, name="email"),
    path('', home_page_view, name="home"),
]

page/models.py
from django.db import models


class NewsModel(models.Model):
    title = models.CharField(max_length=255)
    photo = models.ImageField(upload_to="news")
    description = models.TextField()
    author = models.CharField(max_length=255)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.title} | {self.created_at}"

    class Meta:
        verbose_name = "news"
        verbose_name_plural = "news"


class PopularTourModel(models.Model):
    photo = models.ImageField(upload_to="tours")
    title = models.CharField(max_length=255)
    days = models.PositiveSmallIntegerField(default=0)
    price = models.FloatField(default=0)
    city = models.CharField(max_length=255)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "tour"
        verbose_name_plural = "tours"


class DestinationModel(models.Model):
    photo = models.ImageField(upload_to="destinations")
    country = models.CharField(max_length=255)
    city = models.CharField(max_length=255)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.city} | {self.created_at}"

    class Meta:
        verbose_name = "destination"
        verbose_name_plural = "destinations"


class EmailModel(models.Model):
    email = models.EmailField(unique=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.email} | {self.created_at}"

    class Meta:
        verbose_name = "email"
        verbose_name_plural = "emails"

page/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from page.models import NewsModel, PopularTourModel, DestinationModel, EmailModel


def home_page_view(request):
    news = NewsModel.objects.all().order_by('-created_at')[:3]
    tours = PopularTourModel.objects.all()[:3]
    top_des = DestinationModel.objects.all()[:2]
    bottom_des = DestinationModel.objects.all()[:3]
    context = {
        "news_list": news,
        "tours": tours,
        "top": top_des,
        "bottom": bottom_des,
    }
    return render(request, 'index.html', context)


def new_detail_page(request, pk):
    try:
        news = NewsModel.objects.get(id=pk)
        if news:
            context = {
                "news": news
            }
            return render(request, 'news_item.html', context)
        else:
            return render(request, '404.html')
    except:
        return render(request, '404.html')


def add_email(request):
    if request.method == "POST":
        email = request.POST.get('email')
        user_email = EmailModel.objects.filter(email=email).first()
        if user_email:
            return redirect('page:home')
        new_email = EmailModel.objects.create(
            email=email
        )
        new_email.save()
        return redirect('page:home')

templates/calculator.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Beautiful Calculator</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f0f0f0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
            margin: 0;
        }

        .calculator {
            background-color: #333;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
            padding: 30px;
            text-align: center;
            color: #fff;
            max-width: 400px;
            margin: 0 auto;
        }

        input[type="text"], select {
            padding: 10px;
            margin: 10px 0;
            width: calc(100% - 20px);
            box-sizing: border-box;
            border: none;
            background-color: #555;
            color: #fff;
            border-radius: 5px;
            font-size: 16px;
        }

        select {
            cursor: pointer;
        }

        input[type="submit"] {
            padding: 15px;
            background-color: #4caf50;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
            transition: background-color 0.3s ease;
        }

        input[type="submit"]:hover {
            background-color: #45a049;
        }

        h2 {
            margin-bottom: 20px;
        }

        .result {
            margin-top: 20px;
            font-size: 20px;
        }
    </style>
</head>
<body>
    <div class="calculator">
        <h2>Beautiful Calculator</h2>
        <form method="post" action="{% url 'page:calculator' %}">
            {% csrf_token %}
            <input type="text" name="num1" placeholder="Number 1" required><br>
            <input type="text" name="num2" placeholder="Number 2" required><br>
            <select name="op" required>
                <option value="+">Addition (+)</option>
                <option value="-">Subtraction (-)</option>
                <option value="*">Multiplication (*)</option>
                <option value="/">Division (/)</option>
            </select><br>
            <input type="submit" value="Calculate">
        </form>
        <div class="result" id="result"><h1>{{ result }}</h1></div>
        <div class="result"><h1>History</h1></div>
    </div>

</body>
</html>

templates/footer.html
{% load static %}
<footer class="footer" style="background-image: url('{% static 'images/footer-bg.png' %}')">
    <div class="container">

      <div class="footer-top">

        <ul class="footer-list">

          <li>
            <p class="footer-list-title">Top destination</p>
          </li>

          <li>
            <a href="#" class="footer-link">Indonesia, Jakarta</a>
          </li>

          <li>
            <a href="#" class="footer-link">Maldives, Malé</a>
          </li>

          <li>
            <a href="#" class="footer-link">Australia, Canberra</a>
          </li>

          <li>
            <a href="#" class="footer-link">Thailand, Bangkok</a>
          </li>

          <li>
            <a href="#" class="footer-link">Morocco, Rabat</a>
          </li>

        </ul>

        <ul class="footer-list">

          <li>
            <p class="footer-list-title">Categories</p>
          </li>

          <li>
            <a href="#" class="footer-link">Travel</a>
          </li>

          <li>
            <a href="#" class="footer-link">Lifestyle</a>
          </li>

          <li>
            <a href="#" class="footer-link">Fashion</a>
          </li>

          <li>
            <a href="#" class="footer-link">Education</a>
          </li>

          <li>
            <a href="#" class="footer-link">Food & Drink</a>
          </li>

        </ul>

        <ul class="footer-list">

          <li>
            <p class="footer-list-title">Quick links</p>
          </li>

          <li>
            <a href="#" class="footer-link">About</a>
          </li>

          <li>
            <a href="#" class="footer-link">Contact</a>
          </li>

          <li>
            <a href="#" class="footer-link">Tours</a>
          </li>

          <li>
            <a href="#" class="footer-link">Booking</a>
          </li>

          <li>
            <a href="#" class="footer-link">Terms & Conditions</a>
          </li>

        </ul>

        <div class="footer-list">

          <p class="footer-list-title">Get a newsletter</p>

          <p class="newsletter-text">
            For the latest deals and tips, travel no further than your inbox
          </p>

          <form method="post" action="{% url 'page:email' %}" class="newsletter-form">
              {% csrf_token %}
            <input type="email" name="email" required placeholder="Email address" class="newsletter-input">

            <button type="submit" class="btn btn-primary">Subscribe</button>
          </form>

        </div>

      </div>

      <div class="footer-bottom">

        <a href="#" class="logo">Tourest</a>

        <p class="copyright">
          &copy; 2022 <a href="#" class="copyright-link">codewithsadee</a>. All Rights Reserved
        </p>

        <ul class="social-list">

          <li>
            <a href="#" class="social-link">
              <ion-icon name="logo-facebook"></ion-icon>
            </a>
          </li>

          <li>
            <a href="#" class="social-link">
              <ion-icon name="logo-twitter"></ion-icon>
            </a>
          </li>

          <li>
            <a href="#" class="social-link">
              <ion-icon name="logo-instagram"></ion-icon>
            </a>
          </li>

          <li>
            <a href="#" class="social-link">
              <ion-icon name="logo-linkedin"></ion-icon>
            </a>
          </li>

          <li>
            <a href="#" class="social-link">
              <ion-icon name="logo-google"></ion-icon>
            </a>
          </li>

        </ul>

      </div>

    </div>
  </footer>

templates/header.html
{% load static %}
<header class="header" data-header>
    <div class="container">

      <a href="#">
        <h1 class="logo">Tourest</h1>
      </a>

      <button class="nav-toggle-btn" data-nav-toggle-btn aria-label="Toggle Menu">
        <ion-icon name="menu-outline" class="open"></ion-icon>
        <ion-icon name="close-outline" class="close"></ion-icon>
      </button>

      <nav class="navbar">

        <ul class="navbar-list">

          <li>
            <a href="#" class="navbar-link">Home</a>
          </li>

          <li>
            <a href="#" class="navbar-link">About Us</a>
          </li>

          <li>
            <a href="#" class="navbar-link">Tours</a>
          </li>

          <li>
            <a href="#" class="navbar-link">Destinations</a>
          </li>

          <li>
            <a href="#" class="navbar-link">Blog</a>
          </li>

          <li>
            <a href="#" class="navbar-link">Contact Us</a>
          </li>

        </ul>

        <a href="#" class="btn btn-secondary">Booking Now</a>

      </nav>

    </div>
  </header>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Tourest - Explore the World</title>

  <link rel="shortcut icon" href="{% static 'favicon.svg' %}" type="image/svg+xml">
  <link rel="stylesheet" href="{% static 'css/style.css'%}">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link
    href="https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Comforter+Brush&family=Heebo:wght@400;500;600;700&display=swap"
    rel="stylesheet">

</head>

<body id="top">

  <!-- 
    - #HEADER
  -->

  {% include 'header.html' %}

  <main>
    <article>

      <!-- 
        - #HERO
      -->

      <section class="section hero"
        style="background-image: url('{% static 'images/hero-bg-bottom.png' %}') url('{% static 'images/hero-bg-top.png' %}')">
        <div class="container">

          <img src="{% static 'images/shape-1.png' %}" width="61" height="61" alt="Vector Shape" class="shape shape-1">

          <img src="{% static 'images/shape-2.png' %}" width="56" height="74" alt="Vector Shape" class="shape shape-2">

          <img src="{% static 'images/shape-3.png' %}" width="57" height="72" alt="Vector Shape" class="shape shape-3">

          <div class="hero-content">

            <p class="section-subtitle">Explore Your Travel</p>

            <h2 class="hero-title">Trusted Travel Agency</h2>

            <p class="hero-text">
              I travel not to go anywhere, but to go. I travel for travel's sake the great affair is to move.
            </p>

            <div class="btn-group">
              <a href="#" class="btn btn-primary">Contact Us</a>

              <a href="#" class="btn btn-outline">Learn More</a>
            </div>

          </div>

          <figure class="hero-banner">
            <img src="{% static 'images/hero-banner.png' %}" width="686" height="812" loading="lazy" alt="hero banner"
              class="w-100">
          </figure>

        </div>
      </section>





      <!-- 
        - #DESTINATION
      -->

      <section class="section destination">
        <div class="container">

          <p class="section-subtitle">Destinations</p>

          <h2 class="h2 section-title">Choose Your Place</h2>

          <ul class="destination-list">

              {% for des in top %}
            <li class="w-50">
              <a href="#" class="destination-card">

                <figure class="card-banner">
                  <img src="{{ des.photo.url }}" width="1140" height="1100" loading="lazy"
                    alt="Malé, Maldives" class="img-cover">
                </figure>

                <div class="card-content">
                  <p class="card-subtitle">{{ des.country }}</p>

                  <h3 class="h3 card-title">{{ des.city }}</h3>
                </div>

              </a>
            </li>
              {% endfor %}

          {% for des in bottom %}
            <li>
              <a href="#" class="destination-card">

                <figure class="card-banner">
                  <img src="{{ des.photo.url }}" width="1110" height="480" loading="lazy"
                    alt="Kuala Lumpur, Malaysia" class="img-cover">
                </figure>

                <div class="card-content">
                  <p class="card-subtitle">{{ des.country }}</p>

                  <h3 class="h3 card-title">{{ des.city }}</h3>
                </div>

              </a>
            </li>
          {% endfor %}

          </ul>

        </div>
      </section>





      <!-- 
        - #POPULAR
      -->

      <section class="section popular">
        <div class="container">

          <p class="section-subtitle">Featured Tours</p>

          <h2 class="h2 section-title">Most Popular Tours</h2>

          <ul class="popular-list">
              {% for tour in tours %}
            <li>
              <div class="popular-card">

                <figure class="card-banner">
                  <a href="#">
                    <img src="{{ tour.photo.url }}" width="740" height="518" loading="lazy"
                      alt="Kuala Lumpur, Malaysia" class="img-cover">
                  </a>

                  <span class="card-badge">
                    <ion-icon name="time-outline"></ion-icon>

                    <time datetime="P12D">{{ tour.days }} Days</time>
                  </span>
                </figure>

                <div class="card-content">

                  <div class="card-wrapper">
                    <div class="card-price">From ${{ tour.price }}</div>

                    <div class="card-rating">
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star-outline"></ion-icon>

                      <data value="2">(2)</data>
                    </div>
                  </div>

                  <h3 class="card-title">
                    <a href="#">{{ tour.title }}</a>
                  </h3>

                  <address class="card-location">{{ tour.city }}</address>

                </div>

              </div>
            </li>
              {% endfor %}
          </ul>

        </div>
      </section>





      <!-- 
        - #ABOUT
      -->

      <section class="section about">
        <div class="container">

          <div class="about-content">

            <p class="section-subtitle">About Us</p>

            <h2 class="h2 section-title">Explore all tour of the world with us.</h2>

            <p class="about-text">
              Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or
              randomised words
              which don't look even slightly believable.
            </p>

            <ul class="about-list">

              <li class="about-item">

                <div class="about-item-icon">
                  <ion-icon name="compass"></ion-icon>
                </div>

                <div class="about-item-content">
                  <h3 class="h3 about-item-title">Tour guide</h3>

                  <p class="about-item-text">
                    Lorem Ipsum available, but the majority have suffered alteration in some.
                  </p>
                </div>

              </li>

              <li class="about-item">

                <div class="about-item-icon">
                  <ion-icon name="briefcase"></ion-icon>
                </div>

                <div class="about-item-content">
                  <h3 class="h3 about-item-title">Friendly price</h3>

                  <p class="about-item-text">
                    Lorem Ipsum available, but the majority have suffered alteration in some.
                  </p>
                </div>

              </li>

              <li class="about-item">

                <div class="about-item-icon">
                  <ion-icon name="umbrella"></ion-icon>
                </div>

                <div class="about-item-content">
                  <h3 class="h3 about-item-title">Reliable tour</h3>

                  <p class="about-item-text">
                    Lorem Ipsum available, but the majority have suffered alteration in some.
                  </p>
                </div>

              </li>

            </ul>

            <a href="#" class="btn btn-primary">Booking Now</a>

          </div>

          <figure class="about-banner">
            <img src="{% static 'images/about-banner.png' %}" width="756" height="842" loading="lazy" alt="" class="w-100">
          </figure>

        </div>
      </section>





      <!-- 
        - #BLOG
      -->

      <section class="section blog">
        <div class="container">

          <p class="section-subtitle">From The Blog Post</p>

          <h2 class="h2 section-title">Latest News & Articles</h2>

          <ul class="blog-list">
            {% for news in news_list %}
            <li>
              <div class="blog-card">

                <figure class="card-banner">

                  <a href="#">
                    <img src="{{ news.photo.url }}" width="740" height="518" loading="lazy"
                      alt="A good traveler has no fixed plans and is not intent on arriving." class="img-cover">
                  </a>

                  <span class="card-badge">
                    <ion-icon name="time-outline"></ion-icon>

                    <time datetime="12-04">{{ news.created_at | date }}</time>
                  </span>

                </figure>

                <div class="card-content">

                  <div class="card-wrapper">

                    <div class="author-wrapper">
                      <figure class="author-avatar">
                        <img src="{{ news.photo.url }}" width="30" height="30" alt="Jony bristow">
                      </figure>

                      <div>
                        <a href="#" class="author-name">{{ news.author }}</a>
                      </div>
                    </div>

                    <time class="publish-time" datetime="10:30">{{ news.created_at | time }}</time>

                  </div>

                  <h3 class="card-title">
                    <a href="#">
                      {{ news.title }}
                    </a>
                  </h3>

                  <a href="{% url 'page:news-detail' pk=news.pk %}" class="btn-link">
                    <span>Read More</span>

                    <ion-icon name="arrow-forward-outline" aria-hidden="true"></ion-icon>
                  </a>

                </div>

              </div>
            </li>
            {% endfor %}

          </ul>

        </div>
      </section>

    </article>
  </main>

  {% include 'footer.html' %}


  <!-- 
    - #GO TO TOP
  -->

  <a href="#top" class="go-top" data-go-top aria-label="Go To Top">
    <ion-icon name="chevron-up-outline"></ion-icon>
  </a>




  <script src="{% static 'js/script.js' %}"></script>

  <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

</body>

</html>

templates/news_item.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Tourest - Explore the World</title>

    <!-- 
    - favicon
  -->
    <link rel="shortcut icon" href="{% static 'favicon.svg' %}" type="image/svg+xml" />

    <!-- 
    - custom css link
  -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/news.css' %}"/>


    <!-- 
    - google font link
  -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Comforter+Brush&family=Heebo:wght@400;500;600;700&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    <header class="header" data-header>
      <div class="container">
        <a href="#">
          <h1 class="logo">Tourest</h1>
        </a>

        <button
          class="nav-toggle-btn"
          data-nav-toggle-btn
          aria-label="Toggle Menu"
        >
          <ion-icon name="menu-outline" class="open"></ion-icon>
          <ion-icon name="close-outline" class="close"></ion-icon>
        </button>

        <nav class="navbar">
          <ul class="navbar-list">
            <li>
              <a href="#" class="navbar-link">Home</a>
            </li>

            <li>
              <a href="#" class="navbar-link">About Us</a>
            </li>

            <li>
              <a href="#" class="navbar-link">Tours</a>
            </li>

            <li>
              <a href="#" class="navbar-link">Destinations</a>
            </li>

            <li>
              <a href="#" class="navbar-link">Blog</a>
            </li>

            <li>
              <a href="#" class="navbar-link">Contact Us</a>
            </li>
          </ul>

          <a href="#" class="btn btn-secondary">Booking Now</a>
        </nav>
      </div>
    </header>

    <main>
      <section class="news container">
        <h2 class="title">Lorem ipsum</h2>
        <div class="news_item">
          <div class="item_img ">
            <img src="{{ news.photo.url }}" alt="" />
            <span class="card-badge">
              <ion-icon name="time-outline"></ion-icon>
  
              <time datetime="12-04">{{ news.created_at | date }}</time>
            </span>
            <div class="item_time_1">
              
              <p class="time_text_1">{{ news.created_at | time }}t</p>
            </div>
          </div>
          
          <div class="item_data">
            <div class="item_time">
              
              <p class="time_text">12 days left</p>
            </div>
            <p>
              {{ news.description }}
            </p>
            <a href="{% url 'page:home' %}" class="btn">Back</a>
          </div>
        </div>
      </section>
    </main>

    <!-- 
    - #FOOTER
  -->

    <footer
      class="footer"
      style="background-image: url('{% static 'images/footer-bg.png' %}')"
    >
      <div class="container">
        <div class="footer-top">
          <ul class="footer-list">
            <li>
              <p class="footer-list-title">Top destination</p>
            </li>

            <li>
              <a href="#" class="footer-link">Indonesia, Jakarta</a>
            </li>

            <li>
              <a href="#" class="footer-link">Maldives, Malé</a>
            </li>

            <li>
              <a href="#" class="footer-link">Australia, Canberra</a>
            </li>

            <li>
              <a href="#" class="footer-link">Thailand, Bangkok</a>
            </li>

            <li>
              <a href="#" class="footer-link">Morocco, Rabat</a>
            </li>
          </ul>

          <ul class="footer-list">
            <li>
              <p class="footer-list-title">Categories</p>
            </li>

            <li>
              <a href="#" class="footer-link">Travel</a>
            </li>

            <li>
              <a href="#" class="footer-link">Lifestyle</a>
            </li>

            <li>
              <a href="#" class="footer-link">Fashion</a>
            </li>

            <li>
              <a href="#" class="footer-link">Education</a>
            </li>

            <li>
              <a href="#" class="footer-link">Food & Drink</a>
            </li>
          </ul>

          <ul class="footer-list">
            <li>
              <p class="footer-list-title">Quick links</p>
            </li>

            <li>
              <a href="#" class="footer-link">About</a>
            </li>

            <li>
              <a href="#" class="footer-link">Contact</a>
            </li>

            <li>
              <a href="#" class="footer-link">Tours</a>
            </li>

            <li>
              <a href="#" class="footer-link">Booking</a>
            </li>

            <li>
              <a href="#" class="footer-link">Terms & Conditions</a>
            </li>
          </ul>

          <div class="footer-list">
            <p class="footer-list-title">Get a newsletter</p>

            <p class="newsletter-text">
              For the latest deals and tips, travel no further than your inbox
            </p>

            <form action="" class="newsletter-form">
              <input
                type="email"
                name="email"
                required
                placeholder="Email address"
                class="newsletter-input"
              />

              <button type="submit" class="btn btn-primary">Subscribe</button>
            </form>
          </div>
        </div>

        <div class="footer-bottom">
          <a href="#" class="logo">Tourest</a>

          <p class="copyright">
            &copy; 2022 <a href="#" class="copyright-link">codewithsadee</a>.
            All Rights Reserved
          </p>

          <ul class="social-list">
            <li>
              <a href="#" class="social-link">
                <ion-icon name="logo-facebook"></ion-icon>
              </a>
            </li>

            <li>
              <a href="#" class="social-link">
                <ion-icon name="logo-twitter"></ion-icon>
              </a>
            </li>

            <li>
              <a href="#" class="social-link">
                <ion-icon name="logo-instagram"></ion-icon>
              </a>
            </li>

            <li>
              <a href="#" class="social-link">
                <ion-icon name="logo-linkedin"></ion-icon>
              </a>
            </li>

            <li>
              <a href="#" class="social-link">
                <ion-icon name="logo-google"></ion-icon>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </footer>

    <!-- 
    - custom js link
  -->
    <script src="{% static 'js/script.js' %}"></script>

    <!-- 
    - ionicon link
  -->
    <script
      type="module"
      src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
    ></script>
    <script
      nomodule
      src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"
    ></script>
  </body>
</html>